config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tweets
  resources :users, only: [:index, :show]
  resource :relations, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relation.rb
class Relation < ApplicationRecord
    belongs_to :followed, class_name: "User", foreign_key: :followed_id
    belongs_to :follower, class_name: "User", foreign_key: :follower_id
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    scope :following, ->(followers) { where user_id: followers }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :active_relations, class_name: "Relation", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relations, class_name: "Relation", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relations, source: :followed
  has_many :followers, through: :passive_relations, source: :follower

  def follow(user)
    active_relations.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relations.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followers.include?(user)
  end

  def self.all_except(user)
    where.not(id: user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 

	private

	def sign_up_params 
		params.require(:user).permit(:name, :user_name, :email, :password, :password_confirmation)
	end

	def acount_update_params 
		params.require(:user).permit(:name, :user_name, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def create
    current_user.follow(@user)
    redirect_back fallback_location: root_path

  end

  def destroy
    current_user.unfollow(@user)
    redirect_back fallback_location: root_path
  end

  private
  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.following current_user.following
    @tweet = Tweet.new
    @users = User.all_except(current_user)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
      
    end
  
    def show
        @user = User.find(params[:id])
        @tweets = @user.tweets
        @following = @user.following
        @followers = @user.followers
    end

  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
  	<nav class="navbar is-info">
  		<div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
  			<h1 class="title is-5">Twitter</h1>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
					<span></span>
					<span></span>
					<span></span>
  		</div>
  	 </div>

			<div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          <div class="navbar-item">
					<div class="field is-grouped">
						
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
  	</nav>

    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
  <article class="media box">
		<div class="media-content">
			 <%= render 'tweets/form' %>
		</div>
	</article>
  <% end %>

<% @tweets.each do | tweet | %>
  <div class="box">
  	<article class="media">
  		<div class="media-content">
  			<div class="content">
              <%= link_to user_path(tweet.user) do %>
                <strong><%= tweet.user.name %></strong><br />
  				      <small>@<%= tweet.user.user_name %></small><br/>
            <% end %>
  				<p><%= tweet.tweet %></p>
  			</div>
        <% if user_signed_in? && current_user.id == tweet.user_id %>
  			<nav class="level">
  				<div class="level-left is-mobile">
  					<%= link_to tweet, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_tweet_path(tweet), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" } do %>
  							<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
  			</nav>
        <% end %>
  		</div>
  	</article>
  </div>
<% end %>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :tweet, label: "Tweet about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweet...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/tweets/_list.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Whom to Follow</p>
	<% @users.each do | user | %>
	<div class="panel-block">
		<article class="media">
			<div class="media-content">
				<div class="content">
					<p>
						<%= link_to user_path(user) do %>
						<strong><%= user.name %></strong>
						<small>@<%= user.user_name %></small>
					<% end %>
					</p>
				</div>
			</div>
		</article>
	</div>
    <% end %>
	</nav>
</div>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-content">
					<div class="content">
						<p>
							<%= link_to user_path(current_user) do %>
							<strong><%= current_user.name %></strong><br />
							<small>@<%= current_user.user_name %></small>
							<% end %>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweets</p>
						<p class="title is-6"><%= current_user.tweets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6"><%= current_user.following.count %></p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6"><%= current_user.followers.count %></p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
    		<%= render 'profile' %>
      <% end %>

       <%= render 'feed' %>
       <%= render 'list' %>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/_feed.html.erb
<div class="column is-half">
  
<% @tweets.each do | tweet | %>
  <div class="box">
  	<article class="media">
  		<div class="media-content">
  			<div class="content">
              <%= link_to user_path(tweet.user) do %>
                <strong><%= tweet.user.name %></strong><br />
  				<small>@<%= tweet.user.user_name %></small><br/>
            <% end %>
  				<p><%= tweet.tweet %></p>
  			</div>
        <% if user_signed_in? && current_user.id == tweet.user_id %>
  			<nav class="level">
  				<div class="level-left is-mobile">
  					<%= link_to tweet, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_tweet_path(tweet), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" } do %>
  							<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
  			</nav>
        <% end %>
  		</div>
  	</article>
  </div>
<% end %>
</div>

app/views/users/_list.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Following</p>
	<% @following.each do | following | %>
	<div class="panel-block">
		<article class="media">
			<div class="media-content">
				<div class="content">
					<p>
						<strong><%= following.name %></strong>
						<small>@<%= following.user_name %></small>
					</p>
				</div>
			</div>
		</article>
	</div>
    <% end %>
	</nav>
</div>

<div class="column">
	<nav class="panel">
		<p class="panel-heading">Followers</p>
	<% @followers.each do | follower | %>
	<div class="panel-block">
		<article class="media">
			<div class="media-content">
				<div class="content">
					<p>
						<strong><%= follower.name %></strong>
						<small>@<%= follower.user_name %></small>
					</p>
				</div>
			</div>
		</article>
	</div>
    <% end %>
	</nav>
</div>

app/views/users/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= @user.name %></strong><br />
							<small>@<%= @user.user_name %></small>
						</p>
						<% if @user != current_user %>
                        	<% if @user.following?(current_user) %>
							<p><%= link_to "Unfollow", relations_path(user_id: @user.id),method: :delete, class:"button is-info" %></p>
							<% else %>
							<p><%= link_to "Follow", relations_path(user_id: @user.id),method: :create, class:"button is-info" %></p>
                        	<% end %>
						<% end %>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweets</p>
						<p class="title is-6"><%= @user.tweets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6"><%= @user.following.count %></p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6"><%= @user.followers.count %></p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
    		<%= render 'profile' %>
      <% end %>

       <%= render 'feed' %>
       <%= render 'list' %>
    </div>
  </div>
</section>